const workList = [{
  id:1,
  nombre:"Lampara Atenas",
  tipo:"Lampara colgante",
  precio:4500,
  cuotas:"",
  imagen:"atenas.png",
  p1:"Presentamos nuestro modelo lampara ATENAS",
  p2:"Este diseño es un fuego",
  p3:"Diseñado con el espesor justo para generar una iluminación homogénea en todo el ambiente aportándole vida y estilo.",
  p4:"Consultar por colores disponibles.",
  medidas: "30x30x30 cm",
  precioTachado:"",
  linkDesacarga:"https://www.mercadolibre.com.ar/#from=homecom"
},
{
  id:2,
  nombre:"Velador Grecia",
  tipo:"Lampara velador",
  precio:3000,
  cuotas:"",
  imagen:"calabaza.jpeg",
  p1:"Presentamos nuestro nuevo modelo velador GRECIA",
  p2:"Como todas nuestras lámparas, el velador Grecia es fabricado con un biopolímero amigable con el medio ambiente ",
  p3:"La luz transparenta el material por lo que crea un efecto difuso dándole un toque de calidez y relax a tus ambientes.",
  p4:"Especiales para usar en mesa de luz o escritorio. El modelo de la foto es en color rosa pastel a pedido especial. Consultar por colores disponibles.",
  medidas:"20 x 20 x 20 cm",
  precioTachado:"",
  linkDesacarga:"https://www.mercadolibre.com.ar/#from=homecom"
},
{
  id:3,
  nombre:"Lampara Roma",
  tipo:"Lampara colgante",
  precio:3700,
  cuotas:"",
  imagen:"roma.jpeg",
  p1:"Presentamos nuestro modelo lampara ROMA",
  p2:"Este diseño es un fuego. Lampara lista para su instalación",
  p3:"Incluye florón(tapa del techo), cable de 75cm de largo, prensa cables y portalámparas",
  p4:"Consultar por colores disponibles.",
  medidas:"30 x 27 cm",
  precioTachado:"",
  linkDesacarga:"https://www.mercadolibre.com.ar/#from=homecom"
},
{
  id:4,
  nombre:"Lampara Calabaza",
  tipo:"Lampara colgante",
  precio:3700,
  cuotas:"",
  imagen:"calabaza.jpeg",
  p1:"Presentamos nuestro modelo lampara CALABAZA",
  p2:"Como todas nuestras lámparas, la lampara calabaza es fabricada con un biopolímero amigable con el medio ambiente ",
  p3:"Diseñado con el espesor justo para generar una iluminación homogénea en todo el ambiente aportándole vida y estilo.",
  p4:"Consultar por colores disponibles.",
  medidas:"30 cm de diámetro y 20 cm de alto",
  precioTachado:"",
  linkDesacarga:"https://www.mercadolibre.com.ar/#from=homecom"
},
{
  id:5,
  nombre:"Lampara Finlandia",
  tipo:"Lampara colgante",
  precio:3700,
  cuotas:"",
  imagen:"finlandia.jpeg",
  p1:"Presentamos nuestro modelo lampara FINLANDIA",
  p2:"Diseñado con el espesor justo para generar una iluminación homogénea en todo el ambiente aportándole vida y estilo.",
  p3:"Como todas nuestras lámparas, la lampara finlandia es fabricada con un biopolímero amigable con el medio ambiente ",
  p4:"Consultar por colores disponibles.",
  medidas:"30 x 30 x 30 cm",
  precioTachado:"",
  linkDesacarga:"https://www.mercadolibre.com.ar/#from=homecom"
},
{
  id:6,
  nombre:"Velador Finlandia",
  tipo:"velador",
  precio:3000,
  cuotas:"",
  imagen:"velador_finlandia.jpeg",
  p1:"Presentamos nuestro modelo velador FINLANDIA",
  p2:"Diseñado con el espesor justo para generar una iluminación homogénea en todo el ambiente aportándole vida y estilo.",
  p3:"Como todas nuestras lámparas, el velador finlandia es fabricado con un biopolímero amigable con el medio ambiente ",
  p4:"Especiales para usar en mesa de luz o escritorio. Consultar por colores disponibles.",
  medidas:"20 x 20 x 20 cm",
  precioTachado:"",
  linkDesacarga:"https://www.mercadolibre.com.ar/#from=homecom"
}]
